### ISSUE TITLE
Enhancement for website

### ISSUE THREAD

**Issue by KingQwin520** [RebornXP/rebornxp#1]
You can include a game called "Minesweeper" inside your website!

**Comment by shoaib-jamal** [comment]
@KingQwin520 Thanks for the idea!
I will add **minesweeper** in the _RebornXP AppStore_. **Or** I'll add it directly in the Start Menu.

**Comment by shoaib-jamal** [comment]
### Minesweeper added!
**See Start Menu -> Program Files -> Minesweeper**
